micronaut:
  application:
    name: mnAuthIssue
  security:
    authentication: cookie
    redirect:
      enabled: false
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: sjkfhdshfjjy**#^$&#$JO)#$*#&$*HJKBF:LSDKSA{()W_*D(^*AD&SDSBSANDKLSd
netty:
  default:
    allocator:
      max-order: 3
